
package uasknapsakgreedy;

import java.awt.Frame;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.eyeclose.setVisible(false);
        
        setExtendedState(login.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logusername = new javax.swing.JTextField();
        logpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnregistrasi = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        errorlogin = new javax.swing.JLabel();
        btntentang = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        eyeopen = new javax.swing.JLabel();
        eyeclose = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(22, 160, 133));
        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Selamat Datang");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(360, 220, 170, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("password");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(300, 330, 90, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("username");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(300, 290, 90, 22);
        jPanel4.add(logusername);
        logusername.setBounds(400, 290, 140, 20);
        jPanel4.add(logpassword);
        logpassword.setBounds(400, 330, 140, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("belum punya akun ? silahkan registrasi");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(370, 420, 190, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("silahkan login dengan memasukkan username dan password");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(300, 260, 290, 14);

        btnregistrasi.setBackground(new java.awt.Color(255, 255, 255));
        btnregistrasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasknapsakgreedy/registrasi.png"))); // NOI18N
        btnregistrasi.setText("Registrasi");
        btnregistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrasiActionPerformed(evt);
            }
        });
        jPanel4.add(btnregistrasi);
        btnregistrasi.setBounds(400, 450, 130, 33);

        btnlogin.setBackground(new java.awt.Color(255, 255, 255));
        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasknapsakgreedy/login.png"))); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel4.add(btnlogin);
        btnlogin.setBounds(560, 370, 110, 31);

        errorlogin.setForeground(new java.awt.Color(255, 153, 153));
        errorlogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(errorlogin);
        errorlogin.setBounds(340, 380, 210, 20);

        btntentang.setBackground(new java.awt.Color(255, 255, 255));
        btntentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasknapsakgreedy/about.png"))); // NOI18N
        btntentang.setText("About");
        btntentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntentangActionPerformed(evt);
            }
        });
        jPanel4.add(btntentang);
        btntentang.setBounds(10, 10, 120, 33);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Aplikasi Sistem Trucking (Knapsack  Problem)");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(190, 70, 530, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Menggunakan Algoritma Greedy");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(260, 100, 480, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kelompok 18");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(360, 140, 170, 40);

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasknapsakgreedy/exit.png"))); // NOI18N
        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel4.add(exit);
        exit.setBounds(720, 10, 110, 40);

        eyeopen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasknapsakgreedy/eyeopen.png"))); // NOI18N
        eyeopen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eyeopenMousePressed(evt);
            }
        });
        jPanel4.add(eyeopen);
        eyeopen.setBounds(560, 330, 30, 20);

        eyeclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasknapsakgreedy/eyeclose.png"))); // NOI18N
        eyeclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eyecloseMousePressed(evt);
            }
        });
        jPanel4.add(eyeclose);
        eyeclose.setBounds(560, 330, 40, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasknapsakgreedy/truck.png"))); // NOI18N
        jPanel4.add(jLabel10);
        jLabel10.setBounds(110, 70, 80, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrasiActionPerformed
        // TODO add your handling code here:
        registrasi reg;
        reg = new registrasi();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnregistrasiActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        if(logpassword.getText().equals(registrasi.password)&&(logusername.getText().equals(registrasi.username))){
        //diarahkan ke aplikasi
        aplikasi apl;
        apl = new aplikasi();
        apl.setVisible(true);
        this.dispose();
        }
        else {
            errorlogin.setText("username atau password salah");
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void btntentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntentangActionPerformed
        // TODO add your handling code here:
        aboutview abt = new aboutview();
        abt.setVisible(true);
        abt.pack();
        abt.setLocationRelativeTo(null);
        abt.setDefaultCloseOperation(aboutview.HIDE_ON_CLOSE);
    }//GEN-LAST:event_btntentangActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void eyeopenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeopenMousePressed
        // TODO add your handling code here:
        eyeopen.setVisible(false);
        eyeclose.setVisible(true);
        logpassword.setEchoChar((char)0);
    }//GEN-LAST:event_eyeopenMousePressed

    private void eyecloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyecloseMousePressed
        // TODO add your handling code here:
        eyeopen.setVisible(true);
        eyeclose.setVisible(false);
        logpassword.setEchoChar('•');
        
    }//GEN-LAST:event_eyecloseMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnregistrasi;
    private javax.swing.JButton btntentang;
    private javax.swing.JLabel errorlogin;
    private javax.swing.JButton exit;
    private javax.swing.JLabel eyeclose;
    private javax.swing.JLabel eyeopen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField logpassword;
    private javax.swing.JTextField logusername;
    // End of variables declaration//GEN-END:variables
}
