package uasknapsakgreedy;
public class registrasi extends javax.swing.JFrame {

    /**
     * Creates new form registrasi
     */
    public static String name;
    public static String username;
    public static String password;
    public registrasi() {
        initComponents();
        this.regeyeclose.setVisible(false);
        setExtendedState(registrasi.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        regusername = new javax.swing.JTextField();
        regname = new javax.swing.JTextField();
        reregpassword = new javax.swing.JPasswordField();
        regpassword = new javax.swing.JPasswordField();
        btnsimpan = new javax.swing.JButton();
        passwordnotmatch = new javax.swing.JLabel();
        regeyeclose = new javax.swing.JLabel();
        regeyeopen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(22, 160, 133));
        jPanel2.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("sikahkan isi data kamu");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(340, 160, 130, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Re-type password");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(240, 280, 140, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hallo!");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(360, 120, 70, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(240, 187, 70, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(240, 217, 80, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(240, 250, 70, 25);
        jPanel2.add(regusername);
        regusername.setBounds(380, 220, 140, 20);
        jPanel2.add(regname);
        regname.setBounds(380, 190, 140, 20);
        jPanel2.add(reregpassword);
        reregpassword.setBounds(380, 280, 140, 20);
        jPanel2.add(regpassword);
        regpassword.setBounds(380, 250, 140, 20);

        btnsimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasknapsakgreedy/simpan.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnsimpan);
        btnsimpan.setBounds(450, 340, 120, 40);

        passwordnotmatch.setForeground(new java.awt.Color(255, 153, 153));
        passwordnotmatch.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(passwordnotmatch);
        passwordnotmatch.setBounds(240, 310, 280, 20);

        regeyeclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasknapsakgreedy/eyeclose.png"))); // NOI18N
        regeyeclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                regeyecloseMousePressed(evt);
            }
        });
        jPanel2.add(regeyeclose);
        regeyeclose.setBounds(540, 250, 20, 20);

        regeyeopen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasknapsakgreedy/eyeopen.png"))); // NOI18N
        regeyeopen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                regeyeopenMousePressed(evt);
            }
        });
        jPanel2.add(regeyeopen);
        regeyeopen.setBounds(540, 250, 34, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        
        if(reregpassword.getText().equals(regpassword.getText())){
            name = regname.getText();
            username = regusername.getText();
            password = regpassword.getText();
            
            //diarahkan ke login
            login log;
            log = new login();
            log.setVisible(true);
            this.dispose();
            berhasilsimpan berhasil;
            berhasil = new berhasilsimpan();
            berhasil.setVisible(true);
            this.dispose();
        }else {
         passwordnotmatch.setText("password doesn't match");
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void regeyecloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regeyecloseMousePressed
        // TODO add your handling code here:
        
        regeyeopen.setVisible(true);
        regeyeclose.setVisible(false);
        regpassword.setEchoChar('•');
        reregpassword.setEchoChar('•');
    }//GEN-LAST:event_regeyecloseMousePressed

    private void regeyeopenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regeyeopenMousePressed
        // TODO add your handling code here:
        regeyeopen.setVisible(false);
        regeyeclose.setVisible(true);
        regpassword.setEchoChar((char)0);
        reregpassword.setEchoChar((char)0);
    }//GEN-LAST:event_regeyeopenMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel passwordnotmatch;
    private javax.swing.JLabel regeyeclose;
    private javax.swing.JLabel regeyeopen;
    private javax.swing.JTextField regname;
    private javax.swing.JPasswordField regpassword;
    private javax.swing.JTextField regusername;
    private javax.swing.JPasswordField reregpassword;
    // End of variables declaration//GEN-END:variables
}
