package uasknapsakgreedy;

public class aplikasi extends javax.swing.JFrame {

    /**
     * Creates new form aplikasi
     */
    public aplikasi() {
        initComponents();
        setExtendedState(aplikasi.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        nama.setText(registrasi.name + "!");
    }
    
    public static double dt1 = 0;
    public static double dt2 = 0;
    public static double dt3 = 0;
    public static double dt4 = 0;
    public static double dt5 = 0;
    public static double dt6 = 0;
    public static double dt7 = 0;
    public static double dt8 = 0;
    public static double dt9 = 0;
    public static double dt10 = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        data1 = new javax.swing.JCheckBox();
        data2 = new javax.swing.JCheckBox();
        data3 = new javax.swing.JCheckBox();
        data4 = new javax.swing.JCheckBox();
        data5 = new javax.swing.JCheckBox();
        data6 = new javax.swing.JCheckBox();
        data7 = new javax.swing.JCheckBox();
        data8 = new javax.swing.JCheckBox();
        data9 = new javax.swing.JCheckBox();
        data10 = new javax.swing.JCheckBox();
        berat1 = new javax.swing.JTextField();
        berat2 = new javax.swing.JTextField();
        berat3 = new javax.swing.JTextField();
        berat4 = new javax.swing.JTextField();
        berat5 = new javax.swing.JTextField();
        berat6 = new javax.swing.JTextField();
        berat7 = new javax.swing.JTextField();
        berat8 = new javax.swing.JTextField();
        berat9 = new javax.swing.JTextField();
        berat10 = new javax.swing.JTextField();
        keuntungan1 = new javax.swing.JTextField();
        keuntungan2 = new javax.swing.JTextField();
        keuntungan3 = new javax.swing.JTextField();
        keuntungan4 = new javax.swing.JTextField();
        keuntungan5 = new javax.swing.JTextField();
        keuntungan6 = new javax.swing.JTextField();
        keuntungan7 = new javax.swing.JTextField();
        keuntungan8 = new javax.swing.JTextField();
        keuntungan9 = new javax.swing.JTextField();
        keuntungan10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bobotmax = new javax.swing.JTextField();
        btnproses = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        totalBeratDensity = new javax.swing.JTextField();
        totalKeuntunganDensity = new javax.swing.JTextField();
        noBarangDensity = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalBeratProfit = new javax.swing.JTextField();
        totalKeuntunganProfit = new javax.swing.JTextField();
        noBarangProfit = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        totalBeratWeight = new javax.swing.JTextField();
        totalKeuntunganWeight = new javax.swing.JTextField();
        noBarangWeight = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        warningknapsack = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        warningIsiData = new javax.swing.JLabel();
        warningData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(22, 160, 133));
        jPanel1.setLayout(null);

        nama.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(nama);
        nama.setBounds(280, 10, 190, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selamat datang,");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 10, 150, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasknapsakgreedy/logout.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 10, 110, 27);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA            BERAT(KG)          KEUNTUNGAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 60, 260, 14);

        data1.setText("1");
        data1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data1ActionPerformed(evt);
            }
        });
        jPanel1.add(data1);
        data1.setBounds(10, 80, 40, 23);

        data2.setText("2");
        data2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data2ActionPerformed(evt);
            }
        });
        jPanel1.add(data2);
        data2.setBounds(10, 110, 40, 23);

        data3.setText("3");
        data3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data3ActionPerformed(evt);
            }
        });
        jPanel1.add(data3);
        data3.setBounds(10, 140, 40, 23);

        data4.setText("4");
        data4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data4ActionPerformed(evt);
            }
        });
        jPanel1.add(data4);
        data4.setBounds(10, 170, 40, 23);

        data5.setText("5");
        data5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data5ActionPerformed(evt);
            }
        });
        jPanel1.add(data5);
        data5.setBounds(10, 200, 40, 23);

        data6.setText("6");
        data6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data6ActionPerformed(evt);
            }
        });
        jPanel1.add(data6);
        data6.setBounds(10, 230, 40, 23);

        data7.setText("7");
        data7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data7ActionPerformed(evt);
            }
        });
        jPanel1.add(data7);
        data7.setBounds(10, 260, 40, 23);

        data8.setText("8");
        data8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data8ActionPerformed(evt);
            }
        });
        jPanel1.add(data8);
        data8.setBounds(10, 290, 40, 23);

        data9.setText("9");
        data9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data9ActionPerformed(evt);
            }
        });
        jPanel1.add(data9);
        data9.setBounds(10, 320, 40, 23);

        data10.setText("10");
        data10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data10ActionPerformed(evt);
            }
        });
        jPanel1.add(data10);
        data10.setBounds(10, 350, 40, 23);

        berat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berat1ActionPerformed(evt);
            }
        });
        jPanel1.add(berat1);
        berat1.setBounds(80, 80, 60, 28);
        berat1.setText("0");
        berat1.setEnabled(false);
        jPanel1.add(berat2);
        berat2.setBounds(80, 110, 60, 28);
        berat2.setText("0");
        berat2.setEnabled(false);
        jPanel1.add(berat3);
        berat3.setBounds(80, 140, 60, 28);
        berat3.setText("0");
        berat3.setEnabled(false);
        jPanel1.add(berat4);
        berat4.setBounds(80, 170, 60, 28);
        berat4.setText("0");
        berat4.setEnabled(false);
        jPanel1.add(berat5);
        berat5.setBounds(80, 200, 60, 28);
        berat5.setText("0");
        berat5.setEnabled(false);
        jPanel1.add(berat6);
        berat6.setBounds(80, 230, 60, 28);
        berat6.setText("0");
        berat6.setEnabled(false);
        jPanel1.add(berat7);
        berat7.setBounds(80, 260, 60, 28);
        berat7.setText("0");
        berat7.setEnabled(false);
        jPanel1.add(berat8);
        berat8.setBounds(80, 290, 60, 28);
        berat8.setText("0");
        berat8.setEnabled(false);
        jPanel1.add(berat9);
        berat9.setBounds(80, 320, 60, 28);
        berat9.setText("0");
        berat9.setEnabled(false);
        jPanel1.add(berat10);
        berat10.setBounds(80, 350, 60, 28);
        berat10.setText("0"); berat10.setEnabled(false);
        jPanel1.add(keuntungan1);
        keuntungan1.setBounds(170, 80, 60, 28);
        keuntungan1.setText("0");
        keuntungan1.setEnabled(false);
        jPanel1.add(keuntungan2);
        keuntungan2.setBounds(170, 110, 60, 28);
        keuntungan2.setText("0");
        keuntungan2.setEnabled(false);
        jPanel1.add(keuntungan3);
        keuntungan3.setBounds(170, 140, 60, 28);
        keuntungan3.setText("0");
        keuntungan3.setEnabled(false);
        jPanel1.add(keuntungan4);
        keuntungan4.setBounds(170, 170, 60, 28);
        keuntungan4.setText("0");
        keuntungan4.setEnabled(false);
        jPanel1.add(keuntungan5);
        keuntungan5.setBounds(170, 200, 60, 28);
        keuntungan5.setText("0");
        keuntungan5.setEnabled(false);
        jPanel1.add(keuntungan6);
        keuntungan6.setBounds(170, 230, 60, 28);
        keuntungan6.setText("0");
        keuntungan6.setEnabled(false);
        jPanel1.add(keuntungan7);
        keuntungan7.setBounds(170, 260, 60, 28);
        keuntungan7.setText("0");
        keuntungan7.setEnabled(false);

        keuntungan8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keuntungan8ActionPerformed(evt);
            }
        });
        jPanel1.add(keuntungan8);
        keuntungan8.setBounds(170, 290, 60, 28);
        keuntungan8.setText("0");
        keuntungan8.setEnabled(false);

        keuntungan9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keuntungan9ActionPerformed(evt);
            }
        });
        jPanel1.add(keuntungan9);
        keuntungan9.setBounds(170, 320, 60, 28);
        keuntungan9.setText("0");
        keuntungan9.setEnabled(false);
        jPanel1.add(keuntungan10);
        keuntungan10.setBounds(170, 350, 60, 28);
        keuntungan10.setText("0");
        keuntungan10.setEnabled(false);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JUMLAH BOBOT MAX.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 400, 150, 14);

        bobotmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bobotmaxActionPerformed(evt);
            }
        });
        jPanel1.add(bobotmax);
        bobotmax.setBounds(170, 390, 60, 28);

        btnproses.setText("Proses");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });
        jPanel1.add(btnproses);
        btnproses.setBounds(260, 380, 80, 40);

        jLabel19.setText("TOTAL BERAT");

        jLabel20.setText("TOTAL KEUNTUNGAN");

        jLabel21.setText("NO BARANG");

        totalBeratDensity.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        totalKeuntunganDensity.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        noBarangDensity.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(noBarangDensity)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(totalKeuntunganDensity, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(totalBeratDensity, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addGap(40, 40, 40))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(totalBeratDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(totalKeuntunganDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noBarangDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        totalBeratDensity.setText("0");
        totalBeratDensity.setEnabled(false);
        totalKeuntunganDensity.setText("0");
        totalKeuntunganDensity.setEnabled(false);
        noBarangDensity.setText("0");
        noBarangDensity.setEnabled(false);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(460, 370, 280, 120);

        jLabel4.setText("TOTAL BERAT");

        jLabel5.setText("TOTAL KEUNTUNGAN");

        jLabel6.setText("NO BARANG");

        totalBeratProfit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        totalBeratProfit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBeratProfitActionPerformed(evt);
            }
        });

        totalKeuntunganProfit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        totalKeuntunganProfit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalKeuntunganProfitActionPerformed(evt);
            }
        });

        noBarangProfit.setText("0");
        noBarangProfit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        noBarangProfit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBarangProfitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalBeratProfit)
                    .addComponent(totalKeuntunganProfit)
                    .addComponent(noBarangProfit, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalBeratProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalKeuntunganProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noBarangProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        totalBeratProfit.setText("0");
        totalBeratProfit.setEnabled(false);
        totalKeuntunganProfit.setText("0");
        totalKeuntunganProfit.setEnabled(false);
        noBarangProfit.setEnabled(false);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(460, 50, 280, 130);

        jLabel13.setText("TOTAL BERAT");

        jLabel14.setText("TOTAL KEUNTUNGAN");

        jLabel15.setText("NO BARANG");

        totalBeratWeight.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        totalBeratWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBeratWeightActionPerformed(evt);
            }
        });

        totalKeuntunganWeight.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        noBarangWeight.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalBeratWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(totalKeuntunganWeight)
                    .addComponent(noBarangWeight))
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(totalBeratWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(totalKeuntunganWeight))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(noBarangWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        totalBeratWeight.setText("0");
        totalBeratWeight.setEnabled(false);
        totalKeuntunganWeight.setText("0");
        totalKeuntunganWeight.setEnabled(false);
        noBarangWeight.setText("0");
        noBarangWeight.setEnabled(false);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(460, 220, 280, 120);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("HASIL");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(580, 10, 40, 14);

        warningknapsack.setForeground(new java.awt.Color(255, 153, 153));
        jPanel1.add(warningknapsack);
        warningknapsack.setBounds(50, 460, 330, 20);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(470, 40, 100, 0);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("By Weight");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(390, 190, 160, 20);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("By Density");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(390, 340, 140, 20);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("By Profit");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(390, 30, 120, 14);
        jPanel1.add(warningIsiData);
        warningIsiData.setBounds(40, 430, 240, 0);

        warningData.setForeground(new java.awt.Color(255, 155, 155));
        jPanel1.add(warningData);
        warningData.setBounds(50, 440, 240, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        yakinlogout ylog = new yakinlogout();
        ylog.setVisible(true);
        ylog.pack();
        ylog.setLocationRelativeTo(null);
        ylog.setDefaultCloseOperation(aboutview.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        // TODO add your handling code here:
       if ((data1.isSelected())&&((berat1.getText().isEmpty()||(keuntungan1.getText().isEmpty()))))
       {warningData.setText("Masukan data Berat dan Keuntungan");
       }else if ((data2.isSelected())&&((berat2.getText().isEmpty()||(keuntungan2.getText().isEmpty())))){
        warningData.setText("Masukan data Berat dan Keuntungan");   
       }else if ((data3.isSelected())&&((berat3.getText().isEmpty()||(keuntungan3.getText().isEmpty())))){
        warningData.setText("Masukan data Berat dan Keuntungan");   
       }else if ((data4.isSelected())&&((berat4.getText().isEmpty()||(keuntungan4.getText().isEmpty())))){
        warningData.setText("Masukan data Berat dan Keuntungan");   
       }else if ((data5.isSelected())&&((berat5.getText().isEmpty()||(keuntungan5.getText().isEmpty())))){
        warningData.setText("Masukan data Berat dan Keuntungan");   
       }else if ((data6.isSelected())&&((berat6.getText().isEmpty()||(keuntungan6.getText().isEmpty())))){
        warningData.setText("Masukan data Berat dan Keuntungan");   
       }else if ((data7.isSelected())&&((berat7.getText().isEmpty()||(keuntungan7.getText().isEmpty())))){
        warningData.setText("Masukan data Berat dan Keuntungan");   
       }else if ((data8.isSelected())&&((berat8.getText().isEmpty()||(keuntungan8.getText().isEmpty())))){
        warningData.setText("Masukan data Berat dan Keuntungan");   
       }else if ((data9.isSelected())&&((berat9.getText().isEmpty()||(keuntungan9.getText().isEmpty())))){
        warningData.setText("Masukan data Berat dan Keuntungan");   
       }else if ((data10.isSelected())&&((berat10.getText().isEmpty()||(keuntungan10.getText().isEmpty())))){
        warningData.setText("Masukan data Berat dan Keuntungan"); 
       
       }else {
           warningData.setText("");
       } 
   
       if (bobotmax.getText().isEmpty())
       {warningknapsack.setText("Anda belum memasukan kapasitas knapsack");
        errorkapasitas error = new errorkapasitas();
        error.setVisible(true);
        error.pack();
        error.setLocationRelativeTo(null);
        error.setDefaultCloseOperation(aboutview.HIDE_ON_CLOSE);
       
       }else{
           warningknapsack.setText("");
           Greedy_By_Profit();
           Greedy_By_Weight();
           Greedy_By_Density(); // ki cara manggil tiap proseses. prosese ono 
                              // sesuaikan variabele set. 
       }
    }//GEN-LAST:event_btnprosesActionPerformed

    private void bobotmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bobotmaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bobotmaxActionPerformed

    private void data1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data1ActionPerformed
        // TODO add your handling code here:
        
        if (data1.isSelected())
        {
            berat1.setEnabled(true);
            berat1.setText("");
            keuntungan1.setEnabled(true);
            keuntungan1.setText("");
        }else{
            berat1.setEnabled(false);
            keuntungan1.setEnabled(false);
            berat1.setText("0");
            keuntungan1.setText("0");
        }   
    }//GEN-LAST:event_data1ActionPerformed
    
    public void Greedy_By_Profit(){
        int B1 = Integer.parseInt(berat1.getText());
        int B2 = Integer.parseInt(berat2.getText());
        int B3 = Integer.parseInt(berat3.getText());
        int B4 = Integer.parseInt(berat4.getText());
        int B5 = Integer.parseInt(berat5.getText());
        int B6 = Integer.parseInt(berat6.getText());
        int B7 = Integer.parseInt(berat7.getText());
        int B8 = Integer.parseInt(berat8.getText());
        int B9 = Integer.parseInt(berat9.getText());
        int B10 = Integer.parseInt(berat10.getText());
        int K1 = Integer.parseInt(keuntungan1.getText());
        int K2 = Integer.parseInt(keuntungan2.getText());
        int K3 = Integer.parseInt(keuntungan3.getText());
        int K4 = Integer.parseInt(keuntungan4.getText());
        int K5 = Integer.parseInt(keuntungan5.getText());
        int K6 = Integer.parseInt(keuntungan6.getText());
        int K7 = Integer.parseInt(keuntungan7.getText());
        int K8 = Integer.parseInt(keuntungan8.getText());
        int K9 = Integer.parseInt(keuntungan9.getText());
        int K10 = Integer.parseInt(keuntungan10.getText());
        int w = Integer.parseInt(bobotmax.getText());
        String DataN[]= {"1","2","3","4","5","6","7","8","9","10"};
        int DataB[]= {B1,B2,B3,B4,B5,B6,B7,B8,B9,B10};
        int DataK[]= {K1,K2,K3,K4,K5,K6,K7,K8,K9,K10};
        
        ExchangeSort.ExchangeSortProfit(DataN,DataB,DataK);
        
        int knapsack =0;
        int temp =0;
        int temp1 =0;
        int profit =0;
        String nomerBarang="";
        for (int i=0; i<DataB.length;i++){
            if (knapsack+DataB[i]<=w) {
                temp = DataB[i];
                temp1 = DataK[i];
                knapsack=knapsack+temp;
                profit = profit+temp1;
                if (DataB[i] !=0){
                    nomerBarang=nomerBarang+""+DataN[i]+",";}
                }else{
                temp=0;
                temp1=0;
            }
        } 
        if ( knapsack == 0){
            
        }else{
    totalBeratProfit.setText(""+ knapsack); 
    totalKeuntunganProfit.setText(""+profit);
    noBarangProfit.setText(nomerBarang);
        }  
    } 
    
    private void Greedy_By_Weight(){
        int b1 = Integer.parseInt(berat1.getText());
        int b2 = Integer.parseInt(berat2.getText());
        int b3 = Integer.parseInt(berat3.getText());
        int b4 = Integer.parseInt(berat4.getText());
        int b5 = Integer.parseInt(berat5.getText());
        int b6 = Integer.parseInt(berat6.getText());
        int b7 = Integer.parseInt(berat7.getText());
        int b8 = Integer.parseInt(berat8.getText());
        int b9 = Integer.parseInt(berat9.getText());
        int b10 = Integer.parseInt(berat10.getText());
        int k1 = Integer.parseInt(keuntungan1.getText());
        int k2 = Integer.parseInt(keuntungan2.getText());
        int k3 = Integer.parseInt(keuntungan3.getText());
        int k4 = Integer.parseInt(keuntungan4.getText());
        int k5 = Integer.parseInt(keuntungan5.getText());
        int k6 = Integer.parseInt(keuntungan6.getText());
        int k7 = Integer.parseInt(keuntungan7.getText());
        int k8 = Integer.parseInt(keuntungan8.getText());
        int k9 = Integer.parseInt(keuntungan9.getText());
        int k10 = Integer.parseInt(keuntungan10.getText());
        int w = Integer.parseInt(bobotmax.getText());
        
        String dataN[]= {"1","2","3","4","5","6","7","8","9","10"};
        int dataB[]= {b1,b2,b3,b4,b5,b6,b7,b8,b9,b10};
        int dataK[]= {k1,k2,k3,k4,k5,k6,k7,k8,k9,k10};
       
        ExchangeSort.ExchangeSortWeight(dataN,dataB,dataK);
        
        int knapsack =0;
        int temp1 =0;
        int temp2 =0;
        int profit =0;
        String nomerBarang="";
        for (int i=0; i<dataB.length;i++){
            if (knapsack+dataB[i]<=w) {
                temp1 = dataB[i];
                temp2 = dataK[i];
                knapsack=knapsack+temp1;
                profit = profit+temp2;
                if (dataB[i] !=0){
                    nomerBarang=nomerBarang+""+dataN[i]+",";}
                }else{
                temp1=0;
                temp2=0;
            }
        } 
        totalBeratWeight.setText(""+ knapsack); 
        totalKeuntunganWeight.setText(""+profit);
        noBarangWeight.setText(nomerBarang);
    }
    
    private void Greedy_By_Density(){
        int B1 = Integer.parseInt(berat1.getText());
        int B2 = Integer.parseInt(berat2.getText());
        int B3 = Integer.parseInt(berat3.getText());
        int B4 = Integer.parseInt(berat4.getText());
        int B5 = Integer.parseInt(berat5.getText());
        int B6 = Integer.parseInt(berat6.getText());
        int B7 = Integer.parseInt(berat7.getText());
        int B8 = Integer.parseInt(berat8.getText());
        int B9 = Integer.parseInt(berat9.getText());
        int B10 = Integer.parseInt(berat10.getText());
        int K1 = Integer.parseInt(keuntungan1.getText());
        int K2 = Integer.parseInt(keuntungan2.getText());
        int K3 = Integer.parseInt(keuntungan3.getText());
        int K4 = Integer.parseInt(keuntungan4.getText());
        int K5 = Integer.parseInt(keuntungan5.getText());
        int K6 = Integer.parseInt(keuntungan6.getText());
        int K7 = Integer.parseInt(keuntungan7.getText());
        int K8 = Integer.parseInt(keuntungan8.getText());
        int K9 = Integer.parseInt(keuntungan9.getText());
        int K10 = Integer.parseInt(keuntungan10.getText());
        
        if (B1 != 0){
            dt1 = K1/B1;}
        else {
            dt1=0;}
        if (B2 != 0){ 
            dt2 = K2/B2;
        }else {
            dt2=0;}
        if (B3 != 0){
            dt3 = K3/B3;
        }else {
            dt3=0;}
        if (B4 != 0)
        { dt4 = K4/B4;
        }else {
            dt4=0;}
        if (B5 != 0){ 
            dt5 = K5/K5;
        }else {
            dt5=0;}
        if (B6 != 0){
            dt6 = K6/B6;
        }else {
            dt6=0;}
        if (B7 != 0){ dt7 = K7/B7;
        }else {
            dt7=0;}
        if (B8 != 0){ dt8 = K8/B8;
        }else {
            dt8=0;}
        if (B9 != 0){ dt9 = K9/B9;
        }else {
            dt9=0;}
        if (B10 != 0){ dt10 = K10/B10;
        }else {
            dt10=0;}
        
        int w = Integer.parseInt(bobotmax.getText());
        String data_N[]= {"1","2","3","4","5","6","7","8","9","10"};
        int data_B[]= {B1,B2,B3,B4,B5,B6,B7,B8,B9,B10};
        int data_K[]= {K1,K2,K3,K4,K5,K6,K7,K8,K9,K10};
        double data_D[]= {dt1,dt2,dt3,dt4,dt5,dt6,dt7,dt8,dt9,dt10};
        
        ExchangeSort.ExchangeSortDensity(data_N,data_B,data_K, data_D);
        int knapsack =0;
        int temp1 =0;
        int temp2 =0;
        double temp3 =0;
        int profit =0;
        double density =0;
        String nomer_Barang="";
        
        for (int i=0; i<data_B.length;i++){
            if (knapsack+data_B[i]<=w) {
                temp1 = data_B[i];
                temp2 = data_K[i];
                temp3 = data_D[i];
                knapsack=knapsack+temp1;
                profit = profit+temp2;
                density = density+temp3;
                if (data_B[i] !=0){
                    nomer_Barang=nomer_Barang+""+data_N[i]+",";}
                }else{
                temp1=0;
                temp2=0;
                temp3=0;
            }
        } 
        totalBeratDensity.setText(""+ knapsack); 
        totalKeuntunganDensity.setText(""+profit);
        noBarangDensity.setText(nomer_Barang);
    }
    
    
    private void berat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_berat1ActionPerformed

    private void keuntungan8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keuntungan8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keuntungan8ActionPerformed

    private void keuntungan9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keuntungan9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keuntungan9ActionPerformed

    private void data2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data2ActionPerformed
        // TODO add your handling code here:
        if (data2.isSelected())
        {
            data1.setSelected(true);
            berat1.setEnabled(true);
            berat1.setText("");
            keuntungan1.setEnabled(true);
            keuntungan1.setText("");
            berat2.setEnabled(true);
            berat2.setText("");
            keuntungan2.setEnabled(true);
            keuntungan2.setText("");
        }else{
            data1.setSelected(false);
            berat1.setEnabled(false);
            keuntungan1.setEnabled(false);
            berat1.setText("0");
            keuntungan1.setText("0");
            berat2.setEnabled(false);
            keuntungan2.setEnabled(false);
            berat2.setText("0");
            keuntungan2.setText("0");
        }
    }//GEN-LAST:event_data2ActionPerformed

    private void data3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data3ActionPerformed
        // TODO add your handling code here:
        if (data3.isSelected())
        {
            data1.setSelected(true);
            data2.setSelected(true);
            berat1.setEnabled(true);
            berat1.setText("");
            keuntungan1.setEnabled(true);
            keuntungan1.setText("");
            berat2.setEnabled(true);
            berat2.setText("");
            keuntungan2.setEnabled(true);
            keuntungan2.setText("");
            berat3.setEnabled(true);
            berat3.setText("");
            keuntungan3.setEnabled(true);
            keuntungan3.setText("");
        }else{
            data1.setSelected(false);
            data2.setSelected(false);
            berat1.setEnabled(false);
            keuntungan1.setEnabled(false);
            berat1.setText("0");
            keuntungan1.setText("0");
            berat2.setEnabled(false);
            keuntungan2.setEnabled(false);
            berat2.setText("0");
            keuntungan2.setText("0");
            berat3.setEnabled(false);
            keuntungan3.setEnabled(false);
            berat3.setText("0");
            keuntungan3.setText("0");
        }
    }//GEN-LAST:event_data3ActionPerformed

    private void data4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data4ActionPerformed
        // TODO add your handling code here:
        if (data4.isSelected())
        {
            data1.setSelected(true);
            data2.setSelected(true);
            data3.setSelected(true);
            berat1.setEnabled(true);
            berat1.setText("");
            keuntungan1.setEnabled(true);
            keuntungan1.setText("");
            berat2.setEnabled(true);
            berat2.setText("");
            keuntungan2.setEnabled(true);
            keuntungan2.setText("");
            berat3.setEnabled(true);
            berat3.setText("");
            keuntungan3.setEnabled(true);
            keuntungan3.setText("");
            berat4.setEnabled(true);
            berat4.setText("");
            keuntungan4.setEnabled(true);
            keuntungan4.setText("");
        }else{
            data1.setSelected(false);
            data2.setSelected(false);
            data3.setSelected(false);
            berat1.setEnabled(false);
            keuntungan1.setEnabled(false);
            berat1.setText("0");
            keuntungan1.setText("0");
            berat2.setEnabled(false);
            keuntungan2.setEnabled(false);
            berat2.setText("0");
            keuntungan2.setText("0");
            berat3.setEnabled(false);
            keuntungan3.setEnabled(false);
            berat3.setText("0");
            keuntungan3.setText("0");
            berat4.setEnabled(false);
            keuntungan4.setEnabled(false);
            berat4.setText("0");
            keuntungan4.setText("0");
        }
    }//GEN-LAST:event_data4ActionPerformed

    private void data5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data5ActionPerformed
        // TODO add your handling code here:
        if (data5.isSelected())
        {
            data1.setSelected(true);
            data2.setSelected(true);
            data3.setSelected(true);
            data4.setSelected(true);
            berat1.setEnabled(true);
            berat1.setText("");
            keuntungan1.setEnabled(true);
            keuntungan1.setText("");
            berat2.setEnabled(true);
            berat2.setText("");
            keuntungan2.setEnabled(true);
            keuntungan2.setText("");
            berat3.setEnabled(true);
            berat3.setText("");
            keuntungan3.setEnabled(true);
            keuntungan3.setText("");
            berat4.setEnabled(true);
            berat4.setText("");
            keuntungan4.setEnabled(true);
            keuntungan4.setText("");
            berat5.setEnabled(true);
            berat5.setText("");
            keuntungan5.setEnabled(true);
            keuntungan5.setText("");
        }else{
            data1.setSelected(false);
            data2.setSelected(false);
            data3.setSelected(false);
            data4.setSelected(false);
            berat1.setEnabled(false);
            keuntungan1.setEnabled(false);
            berat1.setText("0");
            keuntungan1.setText("0");
            berat2.setEnabled(false);
            keuntungan2.setEnabled(false);
            berat2.setText("0");
            keuntungan2.setText("0");
            berat3.setEnabled(false);
            keuntungan3.setEnabled(false);
            berat3.setText("0");
            keuntungan3.setText("0");
            berat4.setEnabled(false);
            keuntungan4.setEnabled(false);
            berat4.setText("0");
            keuntungan4.setText("0");
            berat5.setEnabled(false);
            keuntungan5.setEnabled(false);
            berat5.setText("0");
            keuntungan5.setText("0");
        }
    }//GEN-LAST:event_data5ActionPerformed

    private void data6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data6ActionPerformed
        // TODO add your handling code here:
        if (data6.isSelected())
        {
            data1.setSelected(true);
            data2.setSelected(true);
            data3.setSelected(true);
            data4.setSelected(true);
            data5.setSelected(true);
            berat1.setEnabled(true);
            berat1.setText("");
            keuntungan1.setEnabled(true);
            keuntungan1.setText("");
            berat2.setEnabled(true);
            berat2.setText("");
            keuntungan2.setEnabled(true);
            keuntungan2.setText("");
            berat3.setEnabled(true);
            berat3.setText("");
            keuntungan3.setEnabled(true);
            keuntungan3.setText("");
            berat4.setEnabled(true);
            berat4.setText("");
            keuntungan4.setEnabled(true);
            keuntungan4.setText("");
            berat5.setEnabled(true);
            berat5.setText("");
            keuntungan5.setEnabled(true);
            keuntungan5.setText("");
            berat6.setEnabled(true);
            berat6.setText("");
            keuntungan6.setEnabled(true);
            keuntungan6.setText("");
        }else{
            data1.setSelected(false);
            data2.setSelected(false);
            data3.setSelected(false);
            data4.setSelected(false);
            data5.setSelected(false);
            berat1.setEnabled(false);
            keuntungan1.setEnabled(false);
            berat1.setText("0");
            keuntungan1.setText("0");
            berat2.setEnabled(false);
            keuntungan2.setEnabled(false);
            berat2.setText("0");
            keuntungan2.setText("0");
            berat3.setEnabled(false);
            keuntungan3.setEnabled(false);
            berat3.setText("0");
            keuntungan3.setText("0");
            berat4.setEnabled(false);
            keuntungan4.setEnabled(false);
            berat4.setText("0");
            keuntungan4.setText("0");
            berat5.setEnabled(false);
            keuntungan5.setEnabled(false);
            berat5.setText("0");
            keuntungan5.setText("0");
            berat6.setEnabled(false);
            keuntungan6.setEnabled(false);
            berat6.setText("0");
            keuntungan6.setText("0");
        }
    }//GEN-LAST:event_data6ActionPerformed

    private void data7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data7ActionPerformed
        // TODO add your handling code here:
        if (data7.isSelected())
        {
            data1.setSelected(true);
            data2.setSelected(true);
            data3.setSelected(true);
            data4.setSelected(true);
            data5.setSelected(true);
            data6.setSelected(true);
            berat1.setEnabled(true);
            berat1.setText("");
            keuntungan1.setEnabled(true);
            keuntungan1.setText("");
            berat2.setEnabled(true);
            berat2.setText("");
            keuntungan2.setEnabled(true);
            keuntungan2.setText("");
            berat3.setEnabled(true);
            berat3.setText("");
            keuntungan3.setEnabled(true);
            keuntungan3.setText("");
            berat4.setEnabled(true);
            berat4.setText("");
            keuntungan4.setEnabled(true);
            keuntungan4.setText("");
            berat5.setEnabled(true);
            berat5.setText("");
            keuntungan5.setEnabled(true);
            keuntungan5.setText("");
            berat6.setEnabled(true);
            berat6.setText("");
            keuntungan6.setEnabled(true);
            keuntungan6.setText("");
            berat7.setEnabled(true);
            berat7.setText("");
            keuntungan7.setEnabled(true);
            keuntungan7.setText("");
        }else{
            data1.setSelected(false);
            data2.setSelected(false);
            data3.setSelected(false);
            data4.setSelected(false);
            data5.setSelected(false);
            data6.setSelected(false);
            berat1.setEnabled(false);
            keuntungan1.setEnabled(false);
            berat1.setText("0");
            keuntungan1.setText("0");
            berat2.setEnabled(false);
            keuntungan2.setEnabled(false);
            berat2.setText("0");
            keuntungan2.setText("0");
            berat3.setEnabled(false);
            keuntungan3.setEnabled(false);
            berat3.setText("0");
            keuntungan3.setText("0");
            berat4.setEnabled(false);
            keuntungan4.setEnabled(false);
            berat4.setText("0");
            keuntungan4.setText("0");
            berat5.setEnabled(false);
            keuntungan5.setEnabled(false);
            berat5.setText("0");
            keuntungan5.setText("0");
            berat6.setEnabled(false);
            keuntungan6.setEnabled(false);
            berat6.setText("0");
            keuntungan6.setText("0");
            berat7.setEnabled(false);
            keuntungan7.setEnabled(false);
            berat7.setText("0");
            keuntungan7.setText("0");
        }
    }//GEN-LAST:event_data7ActionPerformed

    private void data8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data8ActionPerformed
        // TODO add your handling code here:
        if (data8.isSelected())
        {
            data1.setSelected(true);
            data2.setSelected(true);
            data3.setSelected(true);
            data4.setSelected(true);
            data5.setSelected(true);
            data6.setSelected(true);
            data7.setSelected(true);
            berat1.setEnabled(true);
            berat1.setText("");
            keuntungan1.setEnabled(true);
            keuntungan1.setText("");
            berat2.setEnabled(true);
            berat2.setText("");
            keuntungan2.setEnabled(true);
            keuntungan2.setText("");
            berat3.setEnabled(true);
            berat3.setText("");
            keuntungan3.setEnabled(true);
            keuntungan3.setText("");
            berat4.setEnabled(true);
            berat4.setText("");
            keuntungan4.setEnabled(true);
            keuntungan4.setText("");
            berat5.setEnabled(true);
            berat5.setText("");
            keuntungan5.setEnabled(true);
            keuntungan5.setText("");
            berat6.setEnabled(true);
            berat6.setText("");
            keuntungan6.setEnabled(true);
            keuntungan6.setText("");
            berat7.setEnabled(true);
            berat7.setText("");
            keuntungan7.setEnabled(true);
            keuntungan7.setText("");
            berat8.setEnabled(true);
            berat8.setText("");
            keuntungan8.setEnabled(true);
            keuntungan8.setText("");
        }else{
            data1.setSelected(false);
            data2.setSelected(false);
            data3.setSelected(false);
            data4.setSelected(false);
            data5.setSelected(false);
            data6.setSelected(false);
            data7.setSelected(false);
            berat1.setEnabled(false);
            keuntungan1.setEnabled(false);
            berat1.setText("0");
            keuntungan1.setText("0");
            berat2.setEnabled(false);
            keuntungan2.setEnabled(false);
            berat2.setText("0");
            keuntungan2.setText("0");
            berat3.setEnabled(false);
            keuntungan3.setEnabled(false);
            berat3.setText("0");
            keuntungan3.setText("0");
            berat4.setEnabled(false);
            keuntungan4.setEnabled(false);
            berat4.setText("0");
            keuntungan4.setText("0");
            berat5.setEnabled(false);
            keuntungan5.setEnabled(false);
            berat5.setText("0");
            keuntungan5.setText("0");
            berat6.setEnabled(false);
            keuntungan6.setEnabled(false);
            berat6.setText("0");
            keuntungan6.setText("0");
            berat7.setEnabled(false);
            keuntungan7.setEnabled(false);
            berat7.setText("0");
            keuntungan7.setText("0");
            berat8.setEnabled(false);
            keuntungan8.setEnabled(false);
            berat8.setText("0");
            keuntungan8.setText("0");
        }
    }//GEN-LAST:event_data8ActionPerformed

    private void data9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data9ActionPerformed
        // TODO add your handling code here:
        if (data9.isSelected())
        {
            data1.setSelected(true);
            data2.setSelected(true);
            data3.setSelected(true);
            data4.setSelected(true);
            data5.setSelected(true);
            data6.setSelected(true);
            data7.setSelected(true);
            data8.setSelected(true);
            berat1.setEnabled(true);
            berat1.setText("");
            keuntungan1.setEnabled(true);
            keuntungan1.setText("");
            berat2.setEnabled(true);
            berat2.setText("");
            keuntungan2.setEnabled(true);
            keuntungan2.setText("");
            berat3.setEnabled(true);
            berat3.setText("");
            keuntungan3.setEnabled(true);
            keuntungan3.setText("");
            berat4.setEnabled(true);
            berat4.setText("");
            keuntungan4.setEnabled(true);
            keuntungan4.setText("");
            berat5.setEnabled(true);
            berat5.setText("");
            keuntungan5.setEnabled(true);
            keuntungan5.setText("");
            berat6.setEnabled(true);
            berat6.setText("");
            keuntungan6.setEnabled(true);
            keuntungan6.setText("");
            berat7.setEnabled(true);
            berat7.setText("");
            keuntungan7.setEnabled(true);
            keuntungan7.setText("");
            berat8.setEnabled(true);
            berat8.setText("");
            keuntungan8.setEnabled(true);
            keuntungan8.setText("");
            berat9.setEnabled(true);
            berat9.setText("");
            keuntungan9.setEnabled(true);
            keuntungan9.setText("");
        }else{
            data1.setSelected(false);
            data2.setSelected(false);
            data3.setSelected(false);
            data4.setSelected(false);
            data5.setSelected(false);
            data6.setSelected(false);
            data7.setSelected(false);
            data8.setSelected(false);
            berat1.setEnabled(false);
            keuntungan1.setEnabled(false);
            berat1.setText("0");
            keuntungan1.setText("0");
            berat2.setEnabled(false);
            keuntungan2.setEnabled(false);
            berat2.setText("0");
            keuntungan2.setText("0");
            berat3.setEnabled(false);
            keuntungan3.setEnabled(false);
            berat3.setText("0");
            keuntungan3.setText("0");
            berat4.setEnabled(false);
            keuntungan4.setEnabled(false);
            berat4.setText("0");
            keuntungan4.setText("0");
            berat5.setEnabled(false);
            keuntungan5.setEnabled(false);
            berat5.setText("0");
            keuntungan5.setText("0");
            berat6.setEnabled(false);
            keuntungan6.setEnabled(false);
            berat6.setText("0");
            keuntungan6.setText("0");
            berat7.setEnabled(false);
            keuntungan7.setEnabled(false);
            berat7.setText("0");
            keuntungan7.setText("0");
            berat8.setEnabled(false);
            keuntungan8.setEnabled(false);
            berat8.setText("0");
            keuntungan8.setText("0");
            berat9.setEnabled(false);
            keuntungan9.setEnabled(false);
            berat9.setText("0");
            keuntungan9.setText("0");
        }
    }//GEN-LAST:event_data9ActionPerformed

    private void data10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data10ActionPerformed
        // TODO add your handling code here:
        if (data10.isSelected())
        {
            data1.setSelected(true);
            data2.setSelected(true);
            data3.setSelected(true);
            data4.setSelected(true);
            data5.setSelected(true);
            data6.setSelected(true);
            data7.setSelected(true);
            data8.setSelected(true);
            data9.setSelected(true);
            berat1.setEnabled(true);
            berat1.setText("");
            keuntungan1.setEnabled(true);
            keuntungan1.setText("");
            berat2.setEnabled(true);
            berat2.setText("");
            keuntungan2.setEnabled(true);
            keuntungan2.setText("");
            berat3.setEnabled(true);
            berat3.setText("");
            keuntungan3.setEnabled(true);
            keuntungan3.setText("");
            berat4.setEnabled(true);
            berat4.setText("");
            keuntungan4.setEnabled(true);
            keuntungan4.setText("");
            berat5.setEnabled(true);
            berat5.setText("");
            keuntungan5.setEnabled(true);
            keuntungan5.setText("");
            berat6.setEnabled(true);
            berat6.setText("");
            keuntungan6.setEnabled(true);
            keuntungan6.setText("");
            berat7.setEnabled(true);
            berat7.setText("");
            keuntungan7.setEnabled(true);
            keuntungan7.setText("");
            berat8.setEnabled(true);
            berat8.setText("");
            keuntungan8.setEnabled(true);
            keuntungan8.setText("");
            berat9.setEnabled(true);
            berat9.setText("");
            keuntungan9.setEnabled(true);
            keuntungan9.setText("");
            berat10.setEnabled(true);
            berat10.setText("");
            keuntungan10.setEnabled(true);
            keuntungan10.setText("");
        }else{
            data1.setSelected(false);
            data2.setSelected(false);
            data3.setSelected(false);
            data4.setSelected(false);
            data5.setSelected(false);
            data6.setSelected(false);
            data7.setSelected(false);
            data8.setSelected(false);
            data9.setSelected(false);
            berat1.setEnabled(false);
            keuntungan1.setEnabled(false);
            berat1.setText("0");
            keuntungan1.setText("0");
            berat2.setEnabled(false);
            keuntungan2.setEnabled(false);
            berat2.setText("0");
            keuntungan2.setText("0");
            berat3.setEnabled(false);
            keuntungan3.setEnabled(false);
            berat3.setText("0");
            keuntungan3.setText("0");
            berat4.setEnabled(false);
            keuntungan4.setEnabled(false);
            berat4.setText("0");
            keuntungan4.setText("0");
            berat5.setEnabled(false);
            keuntungan5.setEnabled(false);
            berat5.setText("0");
            keuntungan5.setText("0");
            berat6.setEnabled(false);
            keuntungan6.setEnabled(false);
            berat6.setText("0");
            keuntungan6.setText("0");
            berat7.setEnabled(false);
            keuntungan7.setEnabled(false);
            berat7.setText("0");
            keuntungan7.setText("0");
            berat8.setEnabled(false);
            keuntungan8.setEnabled(false);
            berat8.setText("0");
            keuntungan8.setText("0");
            berat9.setEnabled(false);
            keuntungan9.setEnabled(false);
            berat9.setText("0");
            keuntungan9.setText("0");
            berat10.setEnabled(false);
            keuntungan10.setEnabled(false);
            berat10.setText("0");
            keuntungan10.setText("0");
        }
    }//GEN-LAST:event_data10ActionPerformed

    
    private void totalBeratProfitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBeratProfitActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_totalBeratProfitActionPerformed

    private void totalKeuntunganProfitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalKeuntunganProfitActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_totalKeuntunganProfitActionPerformed

    private void totalBeratWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBeratWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBeratWeightActionPerformed

    private void noBarangProfitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBarangProfitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noBarangProfitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplikasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField berat1;
    private javax.swing.JTextField berat10;
    private javax.swing.JTextField berat2;
    private javax.swing.JTextField berat3;
    private javax.swing.JTextField berat4;
    private javax.swing.JTextField berat5;
    private javax.swing.JTextField berat6;
    private javax.swing.JTextField berat7;
    private javax.swing.JTextField berat8;
    private javax.swing.JTextField berat9;
    private javax.swing.JTextField bobotmax;
    private javax.swing.JButton btnproses;
    private javax.swing.JCheckBox data1;
    private javax.swing.JCheckBox data10;
    private javax.swing.JCheckBox data2;
    private javax.swing.JCheckBox data3;
    private javax.swing.JCheckBox data4;
    private javax.swing.JCheckBox data5;
    private javax.swing.JCheckBox data6;
    private javax.swing.JCheckBox data7;
    private javax.swing.JCheckBox data8;
    private javax.swing.JCheckBox data9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField keuntungan1;
    private javax.swing.JTextField keuntungan10;
    private javax.swing.JTextField keuntungan2;
    private javax.swing.JTextField keuntungan3;
    private javax.swing.JTextField keuntungan4;
    private javax.swing.JTextField keuntungan5;
    private javax.swing.JTextField keuntungan6;
    private javax.swing.JTextField keuntungan7;
    private javax.swing.JTextField keuntungan8;
    private javax.swing.JTextField keuntungan9;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField noBarangDensity;
    private javax.swing.JTextField noBarangProfit;
    private javax.swing.JTextField noBarangWeight;
    private javax.swing.JTextField totalBeratDensity;
    private javax.swing.JTextField totalBeratProfit;
    private javax.swing.JTextField totalBeratWeight;
    private javax.swing.JTextField totalKeuntunganDensity;
    private javax.swing.JTextField totalKeuntunganProfit;
    private javax.swing.JTextField totalKeuntunganWeight;
    private javax.swing.JLabel warningData;
    private javax.swing.JLabel warningIsiData;
    private javax.swing.JLabel warningknapsack;
    // End of variables declaration//GEN-END:variables
}
